### ISSUE TITLE
Idioma Brazilian Portuguese não rola

### ISSUE THREAD

**Issue by AlexandreChagas** [simplesconsultoria/collective.texttospeech#12]
Boa tarde amigos, 

fiz alguns testes utilizando instalações zeradas dos plones:

No geral, quando habilito o idioma Brazilian Portuguese fica mudo.

* no Plone 4.3.8 : aparentemente funciona somente com os três primeiros idiomas, mas funciona:

UK English Female
UK English Male e US English Female

Em seguida, instalando a IDG 1.1.4 trava geral após pressionar o botão "play"

------

* no Plone 4.3.7 : Também... aparentemente funciona somente com os três primeiros idiomas e quanto a utilização da IDG, NÃO trava :)

Versão utilizada: 1.0a2

Abraço,

Alexandre Chagas

**Comment by hvelarde** [comment]
@AlexandreChagas do you mind using English as the language for this issue tracker?

I have a working instance of Plone 4.3.8 with collective.texttospeech 1.0a2 installed and configured with `Brazilian Portuguese Female`.

you must provide additional information like any JavaScript error in the browser console, or I'll have to close this as invalid.

also note that this package is not yet approved to be installed on IDGB and we have no resources currently allocated to test it there.
